var STRINGS = {};

STRINGS.GLOBAL_LOADING = 'Loading...';
STRINGS.GLOBAL_REDIRECTING = 'Redirecting...';

STRINGS.LOGIN_PLACEHOLDER_USERNAME = 'Username';
STRINGS.LOGIN_PLACEHOLDER_PASSWORD = 'Minimum 8 Characters';
STRINGS.LOGIN_VALIDATION_EMAIL = 'You must provide a valid e-mail address';
STRINGS.LOGIN_VALIDATION_PASSWORD_LENGTH = 'Password must be at least 8 characters';
STRINGS.LOGIN_SERVER_RESPONSE_EMAIL_PASSWORD = 'Invalid E-Mail or Password';
STRINGS.LOGIN_SERVER_RESPONSE_ACCOUNT = 'Account Not Found';
STRINGS.LOGIN_SERVER_RESPONSE_GENERIC = 'An Error Has Occured';

module.exports = STRINGS;